package parse

import (
	"github.com/hashicorp/hcl/v2"
	"github.com/turbot/pipe-fittings/v2/modconfig"
)

func GetMetadataForParsedResource(resourceName string, srcRange hcl.Range, fileData map[string][]byte, mod *modconfig.Mod) (*modconfig.ResourceMetadata, error) {
	// convert the name into a short name
	parsedName, err := modconfig.ParseResourceName(resourceName)
	if err != nil {
		return nil, err
	}
	m := &modconfig.ResourceMetadata{
		ResourceName:     parsedName.Name,
		FileName:         srcRange.Filename,
		StartLineNumber:  srcRange.Start.Line,
		EndLineNumber:    srcRange.End.Line,
		IsAutoGenerated:  false,
		SourceDefinition: getSourceDefinition(srcRange, fileData),
	}
	// update the 'ModName' and 'ModShortName' fields
	m.SetMod(mod)
	return m, nil
}

func getSourceDefinition(sourceRange hcl.Range, fileData map[string][]byte) string {
	filename := sourceRange.Filename
	fileBytes, ok := fileData[filename]
	if !ok {
		return ""
	}

	// Find byte offsets for start and end lines without splitting the entire file.
	// This avoids allocating a slice of all lines which was causing 62% of allocations.
	startLine := sourceRange.Start.Line
	endLine := sourceRange.End.Line

	if startLine < 1 {
		startLine = 1
	}

	var startOffset, endOffset int
	currentLine := 1

	// Find start offset (beginning of startLine)
	for i := 0; i < len(fileBytes); i++ {
		if currentLine == startLine {
			startOffset = i
			break
		}
		if fileBytes[i] == '\n' {
			currentLine++
		}
	}

	// Find end offset (end of endLine, or EOF)
	endOffset = len(fileBytes)
	for i := startOffset; i < len(fileBytes); i++ {
		if fileBytes[i] == '\n' {
			if currentLine == endLine {
				endOffset = i
				break
			}
			currentLine++
		}
	}

	return string(fileBytes[startOffset:endOffset])
}
