package modconfig

import "github.com/hashicorp/hcl/v2"

// ResourceMetadata ius a struct containing additional data
// about each resource, used to populate the introspection tables
type ResourceMetadata struct {
	// required to allow partial decoding
	ResourceMetadataRemain hcl.Body `hcl:",remain" json:"-"`

	ResourceName string `column:"resource_name,text," json:"resource_name"`
	// mod short name
	ModName          string `column:"mod_name,text" json:"mod_name"`
	FileName         string `column:"file_name,text" json:"file_name"`
	StartLineNumber  int    `column:"start_line_number,integer" json:"start_line_number"`
	EndLineNumber    int    `column:"end_line_number,integer" json:"end_line_number"`
	IsAutoGenerated  bool   `column:"auto_generated,bool" json:"auto_generated"`
	SourceDefinition string `column:"source_definition,text" json:"source_definition"`
	Anonymous        bool   `column:"is_anonymous,bool" json:"is_anonymous"`
	ModFullName      string `json:"-"`
}

// SetMod sets the mod name and mod short name
func (m *ResourceMetadata) SetMod(mod *Mod) {
	// if the mod is the auto-generated default workspace mod, do not save in metadata
	if mod.IsDefaultMod() {
		return
	}
	m.ModName = mod.ShortName
	m.ModFullName = mod.FullName
}

func (m *ResourceMetadata) Clone() ResourceMetadata {
	return ResourceMetadata{
		ResourceName:     m.ResourceName,
		ModName:          m.ModName,
		FileName:         m.FileName,
		StartLineNumber:  m.StartLineNumber,
		EndLineNumber:    m.EndLineNumber,
		IsAutoGenerated:  m.IsAutoGenerated,
		SourceDefinition: m.SourceDefinition,
		ModFullName:      m.ModFullName,
		Anonymous:        m.Anonymous,
	}
}
