name: Go Lint and Test
on:
  push:
    tags:
      - v*
    branches:
      - main
      - "v*"
      - pp
      - pp-rebuilt
  workflow_dispatch:
  pull_request:

env:
  GOPRIVATE: github.com/turbot/*

jobs:
  golangci:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pipe-fittings repository
        uses: actions/checkout@v3

      # this is required, check golangci-lint-action docs
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false # setup-go v4 caches by default, do not change this parameter, check golangci-lint-action doc: https://github.com/golangci/golangci-lint-action/pull/704

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.1
          args: --timeout=15m

      - name: Run tests
        run: make test